name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read
  checks: write  # Required for test-reporter action
  statuses: write

jobs:
  test:
    runs-on: macos-latest
    # NetWatcher requires Apple's system Python due to code signing requirements
    # for CoreLocation framework. Cannot use setup-python action.

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify system Python
      run: |
        # Use Apple's system Python (required for CoreLocation)
        /usr/bin/python3 --version
        which python3
        /usr/bin/python3 -m pip --version || echo "pip not available"

    - name: Install pip if needed
      run: |
        # Ensure pip is available
        if ! /usr/bin/python3 -m pip --version 2>/dev/null; then
          echo "Installing pip..."
          curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
          /usr/bin/python3 get-pip.py --user
          rm get-pip.py
        fi

    - name: Install system dependencies (macOS)
      run: |
        # Install pacparser if needed (usually via brew)
        brew install pacparser || echo "pacparser already installed or not available"

    - name: Install Python dependencies
      run: |
        /usr/bin/python3 -m pip install --upgrade pip setuptools wheel --user
        # Editable install needs to go to site-packages, not --user
        /usr/bin/python3 -m pip install -e ".[test]"

    - name: Verify installation
      run: |
        /usr/bin/python3 -c "import src; print('NetWatcher imported successfully')"
        /usr/bin/python3 -m pytest --version

    - name: Run tests with pytest
      run: |
        /usr/bin/python3 -m pytest tests/ -v --tb=short --junit-xml=test-results.xml

    - name: Run tests with coverage
      run: |
        /usr/bin/python3 -m pytest tests/ --cov=src --cov-report=xml --cov-report=html --cov-report=term-missing

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          test-results.xml
          htmlcov/

    - name: Test report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Test Results
        path: test-results.xml
        reporter: java-junit
        fail-on-error: false

  lint:
    runs-on: macos-latest
    # NetWatcher requires Apple's system Python

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Verify system Python
      run: |
        /usr/bin/python3 --version
        /usr/bin/python3 -m pip --version || echo "pip not available"

    - name: Install dependencies
      run: |
        /usr/bin/python3 -m pip install --upgrade pip --user
        # Editable install works better without --user flag
        /usr/bin/python3 -m pip install -e ".[dev]"

    - name: Lint with ruff
      run: |
        /usr/bin/python3 -m ruff check src/ --output-format=github
